services:
  bash-app:
    build: ./bash-app
    image: pastbenjay/bash-app:latest
    container_name: bash-app
    environment:
      - NAME=Intern

  java-app:
    build: ./java-app
    image: pastbenjay/java-app:latest
    container_name: java-app
    environment:
      - NAME=Intern

  python-app:
    build: ./python-app
    image: pastbenjay/python-app:latest
    container_name: python-app
    environment:
      - NAME=Intern