apiVersion: batch/v1
kind: Job
metadata:
  name: python-app
  namespace: intern-app
spec:
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: pastbenjay/python-app:latest
          env:
            - name: NAME
              value: "Intern"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
      restartPolicy: Never
  backoffLimit: 0
